# Assignment 4 for Course 1MS041
Make         sure you pass the `# ... Test` cells and
 submit your solution notebook in the corresponding assignment on the course website. You can submit multiple times before the deadline         and your highest score will be used.

---
## Assignment 4, PROBLEM 1
Maximum Points = 1


The goal of this problem is to implement your own random projection function, i.e. same as in the random projection theorem and Johnson Lindenstrauss. Below you will find a function template, as always fill in XXX.

Some notes, the input will be a numpy array and the output should also be a numpy array. The format for the input is `(n_samples, d)` and the output should be of the form `(n_samples, k)`.

In [4]:
# Do not rename the function below just replace what is XXX
def random_projection(X,d,k):
    '''Perform a random projection of the dataset X from 
    d-dimensions into k-dimensions'''
    assert X.shape[1] == d, "The array X does not have the shape (n_samples,d)"
    a = np.random.normal(size=(d,k))
    print(X)
    print(a)
    y = (1/np.sqrt(k))*np.mat(X)*np.mat(a)
    return y

In [5]:
import numpy as np

In [ ]:
np.random.seed(1)
    v_pre = np.random.normal(size=d)
    v = v_pre / np.linalg.norm(v_pre)

In [6]:
X_test = np.array([[1,1],[2,1],[3,1],[4,1]])
random_projection(X_test,2,1)

[[1 1]
 [2 1]
 [3 1]
 [4 1]]
[[-1.18054483]
 [-0.14563628]]


matrix([[-1.32618111],
        [-2.50672594],
        [-3.68727077],
        [-4.8678156 ]])

---
#### Local Test for Assignment 4, PROBLEM 1
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [32]:
# small test to see that you output the correct shape
import numpy as np
X_test = np.array([[1,1],[2,1],[3,1],[4,1]])
try:
    assert(random_projection(X_test,2,1).shape == (X_test.shape[0],1))
    print("You are outputting the correct dimension, hopefully it is correct.")
except AssertionError:
    print("Try again! and make sure you are producing an output of (n_samples,k)")

You are outputting the correct dimension, hopefully it is correct.


---
## Assignment 5, PROBLEM 2
Maximum Points = 2


Write a function that generates points from a unit ball and unit sphere in $d$ dimensions. The output should be a numpy array of shape `(n_samples,d)`. As always replace XXX with whatever makes sense.

Hint, numpy has a function called power, https://numpy.org/doc/stable/reference/generated/numpy.power.html
also remember `numpy.linalg.norm` to calculate length of vectors.

Another hint that might be useful, note that numpy has broadcasting rule in order to make sense of the multiplication between different size vectors. Say we would like to compute the product of a (10,10) vector and a (10,1) vector, in this case numpy will broadcast the second vector to (10,10) by copying the values along the second axis. However for this to work they both have to have the same number of dimensions, i.e. we cannot multiply (10,10) and (10,) we have to reshape the second vector to (10,1) for broadcasting to work).

---
## Assignment 4, PROBLEM 2
Maximum Points = 2

In [18]:
# Do not rename the function below just replace what is XXX
def uniform_unit_ball(n_samples=1,d=1,surface=False):
    '''Generate n_samples uniform random samples from the unit ball in d-dimensions.
    If surface==True generate only from the surface of the ball'''
    assert (type(n_samples) == Integer) or (type(n_samples) == int), "samples needs to be integer"
    assert (type(d) == Integer) or (type(d) == int), "d needs to be integer"
    assert (n_samples > 0), "Positive number of samples"
    assert (d >= 1), "Dimension needs to be greater than or equal to 1"
    
    XY = np.random.normal(size=(n_samples,d)) # Spherical Gaussian with unit variance in each coordinate in R^2
    XY = XY / np.linalg.norm(XY,axis=1).reshape(-1,1) # Make all vector unit length
    r = np.random.uniform(size=(n_samples,d))^(1/d) ## this is becase it's square rooted by the size of the dimension 
    #uniform_ball = np.sqrt(r)*XY # Consider the correctly scaled radius    
        
    if surface == True:
        return r*XY
    else:
        return r

In [ ]:
#Comes from here - notes 16

XY = np.random.normal(size=(n_samples,d)) # Spherical Gaussian with unit variance in each coordinate in R^2
XY = XY / np.linalg.norm(XY,axis=1).reshape(-1,1) # Make all vector unit length
r = np.random.uniform(size=(XY.shape[0],1)) # Sample the radii uniformly from [0,1]
uniform_ball = np.sqrt(r)*XY # Consider the correctly scaled radius

---
#### Local Test for Assignment 4, PROBLEM 2
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [20]:

# Use the below visual verification in two dimension to see if you generate uniform samples
# from the 2d ball
def sage_histogram2d(data_x,data_y, bins=10, normed=False):
    import numpy as np
    from sage.plot.plot3d.shapes import Box
    counts, x_edges, y_edges = np.histogram2d(data_x,data_y,normed=normed,bins=bins)
    width = np.mean(np.diff(x_edges))
    depth = np.mean(np.diff(y_edges))
    XX,YY =  np.meshgrid(x_edges[:-1],y_edges[:-1])
    show(sum([Box((width/2,depth/2,c/2)).translate(x+width/2,y+depth/2,c/2) for x,y,c in zip(XX.reshape(-1),YY.reshape(-1),counts.reshape(-1)) if c > 0]))



unif_ball = uniform_unit_ball(10000,2,surface=True) #Change to true if you want to see if your code works
sage_histogram2d(unif_ball[:,0],unif_ball[:,1],normed=True)

Graphics3d Object

In [42]:
unif_ball = uniform_unit_ball(1000000,2,surface=True) #Change to true if you want to see if your code works
sage_histogram2d(unif_ball[:,0],unif_ball[:,1],normed=True)

Graphics3d Object

---
## Assignment 5, PROBLEM 3
Maximum Points = 1


Perform the following three steps, then answer the question:

1. Generate 200 points from the surface of the unit ball in 50 dimensions (use your solution from problem 2).
2. Generate a few random lines through the origin and plot the distribution of points on each line.
3. What does your result from 2 say about where the surface area is concentrated relative to each line

---
## Assignment 4, PROBLEM 3
Maximum Points = 1

In [25]:
# Dont edit the below array, use the index corresponding to the correct answer
problem3_multiple_choice = ['On the north and south pole according to the line',
                            'Uniformly distributed over [-1,1]',
                            'Around the equator orthogonal to the line',
                            'This depends on the line, we get a different distribution each time']

problem3_answer = problem3_multiple_choice[2]

---
#### Local Test for Assignment 4, PROBLEM 3
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [26]:
# test that your answer is one of the possible answers
problem3_multiple_choice = ['On the north and south pole according to the line',
                            'Uniformly distributed over [-1,1]',
                            'Around the equator orthogonal to the line',
                            'This depends on the line, we get a different distribution each time']

assert (problem3_answer in problem3_multiple_choice), "Please select on of the answers"

---
## Assignment 4, PROBLEM 4
Maximum Points = 1


Why does `findSingularVectors` give rise to no-convergence sometimes, specially when we try to extract many singular vectors, say trying to extract 6 singular vectors from 10-d gaussian random vectors?

In [67]:
# Write your answer by filling in the string, this is free text
problem4_answer = 'XXX'

---
#### Local Test for Assignment 4, PROBLEM 4
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [68]:
# test that your answer is a string
assert (type(problem4_answer) == str), "Make sure that your answer is a single string"

---
## Assignment 4, PROBLEM 5
Maximum Points = 3


Use the power method to compute the first 5 singular vectors for the matrix `problem5_Z` found below. Compute each singular vector to the tolerance of $10^{-6}$, in the following sense, (call $Z=$ `problem5_Z`)
$$
    \left \| v - \frac{Z^T Z v}{\|Z^T Z v\|} \right \| < 10^{-6}.
$$
for the proposed singular unit vector $v$.

In [164]:
import numpy as np

problem5_Z = np.array([[ 1.21395528,  0.61319117,  0.96775704,  0.47560786,  0.46944868,
                        -0.96174286, -0.04597716,  1.11423879, -2.16790516,  1.41559609],
                       [-1.74579582, -2.96579703, -1.53883473, -2.08891653, -2.51835633,
                         0.28005013,  3.14477698,  0.27859531, -0.21063502,  1.21238791],
                       [-1.38846711, -2.36561478,  2.00400938, -0.81219207,  0.76351148,
                        -0.94135869,  1.81624568,  0.30603084,  0.4502897 , -1.68275369],
                       [-0.83770176, -1.12651679,  0.72947716,  0.28293936, -1.54650026,
                         1.47451872,  0.58828722,  2.63367002, -1.75123164,  0.20599531],
                       [ 0.16922431,  0.07605318,  0.87850331,  0.45439765, -0.36589416,
                        -1.16866643,  1.00148338, -2.24790302, -1.03375691,  0.66441057],
                       [ 0.18417791, -0.6944261 ,  0.11811434, -0.02291727, -3.49209616,
                         2.567174  , -0.79506183, -0.61917615, -0.25294073, -0.44972644],
                       [ 0.21973089,  0.58409936,  0.05358338,  0.09448722,  1.18545664,
                         0.09458799, -1.45002309,  1.38528763, -0.26669331, -0.02398977],
                       [-0.77246978, -1.29899321,  0.32673874,  0.41253631,  0.9496008 ,
                         0.23276985, -0.44480295, -1.70329931,  0.74889995,  0.10723953],
                       [ 0.87892498,  1.51055297,  0.99208142,  0.15116986, -0.419831  ,
                        -1.51231948,  2.44759401, -0.34096878,  0.78995641,  0.1464366 ],
                       [ 0.4855678 , -0.49584481,  0.97413157, -1.44802482,  0.4773462 ,
                         0.08619087, -1.15799392, -0.3331743 , -1.40555249, -0.76420582]])

# replace XXX with the computed singular vectors put together in a numpy array of the shape
# (5,10). So each row is a singular vector and ordered in decending order:
# first singular vector on first row etc.

first_five_singular_vectors = XXX

NameError: name 'XXX' is not defined